// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: proto/open_platform/open.proto

package open

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushSMSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignId     string   `protobuf:"bytes,1,opt,name=sign_id,json=signId,proto3" json:"sign_id,omitempty"`
	TemplateId string   `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Phone      string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Params     []string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
}

func (x *PushSMSRequest) Reset() {
	*x = PushSMSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_open_platform_open_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushSMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSMSRequest) ProtoMessage() {}

func (x *PushSMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_open_platform_open_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSMSRequest.ProtoReflect.Descriptor instead.
func (*PushSMSRequest) Descriptor() ([]byte, []int) {
	return file_proto_open_platform_open_proto_rawDescGZIP(), []int{0}
}

func (x *PushSMSRequest) GetSignId() string {
	if x != nil {
		return x.SignId
	}
	return ""
}

func (x *PushSMSRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *PushSMSRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PushSMSRequest) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type PushSMSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fee uint64 `protobuf:"varint,1,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (x *PushSMSResponse) Reset() {
	*x = PushSMSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_open_platform_open_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushSMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSMSResponse) ProtoMessage() {}

func (x *PushSMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_open_platform_open_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSMSResponse.ProtoReflect.Descriptor instead.
func (*PushSMSResponse) Descriptor() ([]byte, []int) {
	return file_proto_open_platform_open_proto_rawDescGZIP(), []int{1}
}

func (x *PushSMSResponse) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

type SMSTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId  string `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Content     string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ParamNumber int32  `protobuf:"varint,3,opt,name=param_number,json=paramNumber,proto3" json:"param_number,omitempty"`
}

func (x *SMSTemplate) Reset() {
	*x = SMSTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_open_platform_open_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMSTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSTemplate) ProtoMessage() {}

func (x *SMSTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_open_platform_open_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSTemplate.ProtoReflect.Descriptor instead.
func (*SMSTemplate) Descriptor() ([]byte, []int) {
	return file_proto_open_platform_open_proto_rawDescGZIP(), []int{2}
}

func (x *SMSTemplate) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SMSTemplate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SMSTemplate) GetParamNumber() int32 {
	if x != nil {
		return x.ParamNumber
	}
	return 0
}

type GetAllSMSTemplatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllSMSTemplatesRequest) Reset() {
	*x = GetAllSMSTemplatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_open_platform_open_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllSMSTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSMSTemplatesRequest) ProtoMessage() {}

func (x *GetAllSMSTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_open_platform_open_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSMSTemplatesRequest.ProtoReflect.Descriptor instead.
func (*GetAllSMSTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_open_platform_open_proto_rawDescGZIP(), []int{3}
}

type GetAllSMSTemplatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Templates []*SMSTemplate `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
}

func (x *GetAllSMSTemplatesResponse) Reset() {
	*x = GetAllSMSTemplatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_open_platform_open_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllSMSTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSMSTemplatesResponse) ProtoMessage() {}

func (x *GetAllSMSTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_open_platform_open_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSMSTemplatesResponse.ProtoReflect.Descriptor instead.
func (*GetAllSMSTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_open_platform_open_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllSMSTemplatesResponse) GetTemplates() []*SMSTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type PushEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To         string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"` // target email address
	Subject    string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	TemplateId string   `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // email template id
	Params     []string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`                           // template param set
}

func (x *PushEmailRequest) Reset() {
	*x = PushEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_open_platform_open_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEmailRequest) ProtoMessage() {}

func (x *PushEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_open_platform_open_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEmailRequest.ProtoReflect.Descriptor instead.
func (*PushEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_open_platform_open_proto_rawDescGZIP(), []int{5}
}

func (x *PushEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *PushEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PushEmailRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *PushEmailRequest) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type PushEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushEmailResponse) Reset() {
	*x = PushEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_open_platform_open_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEmailResponse) ProtoMessage() {}

func (x *PushEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_open_platform_open_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEmailResponse.ProtoReflect.Descriptor instead.
func (*PushEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_open_platform_open_proto_rawDescGZIP(), []int{6}
}

type EmailTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId  string `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Content     string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ParamNumber int32  `protobuf:"varint,3,opt,name=param_number,json=paramNumber,proto3" json:"param_number,omitempty"`
	Alias       string `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
}

func (x *EmailTemplate) Reset() {
	*x = EmailTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_open_platform_open_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTemplate) ProtoMessage() {}

func (x *EmailTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_open_platform_open_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTemplate.ProtoReflect.Descriptor instead.
func (*EmailTemplate) Descriptor() ([]byte, []int) {
	return file_proto_open_platform_open_proto_rawDescGZIP(), []int{7}
}

func (x *EmailTemplate) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *EmailTemplate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmailTemplate) GetParamNumber() int32 {
	if x != nil {
		return x.ParamNumber
	}
	return 0
}

func (x *EmailTemplate) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type GetAllEmailTemplatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllEmailTemplatesRequest) Reset() {
	*x = GetAllEmailTemplatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_open_platform_open_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllEmailTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmailTemplatesRequest) ProtoMessage() {}

func (x *GetAllEmailTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_open_platform_open_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmailTemplatesRequest.ProtoReflect.Descriptor instead.
func (*GetAllEmailTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_open_platform_open_proto_rawDescGZIP(), []int{8}
}

type GetAllEmailTemplatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Templates []*EmailTemplate `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
}

func (x *GetAllEmailTemplatesResponse) Reset() {
	*x = GetAllEmailTemplatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_open_platform_open_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllEmailTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmailTemplatesResponse) ProtoMessage() {}

func (x *GetAllEmailTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_open_platform_open_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmailTemplatesResponse.ProtoReflect.Descriptor instead.
func (*GetAllEmailTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_open_platform_open_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllEmailTemplatesResponse) GetTemplates() []*EmailTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

var File_proto_open_platform_open_proto protoreflect.FileDescriptor

var file_proto_open_platform_open_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x76, 0x31, 0x22, 0x78, 0x0a, 0x0e, 0x50, 0x75, 0x73, 0x68, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x23, 0x0a, 0x0f,
	0x50, 0x75, 0x73, 0x68, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x66, 0x65,
	0x65, 0x22, 0x6b, 0x0a, 0x0b, 0x53, 0x4d, 0x53, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x1b,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x4d, 0x53, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x4d, 0x53, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x09, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x4d, 0x53, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x09, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x22, 0x75, 0x0a, 0x10, 0x50, 0x75, 0x73, 0x68, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x13, 0x0a,
	0x11, 0x50, 0x75, 0x73, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x0d, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x1d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5d, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x09, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x32, 0xcd, 0x01, 0x0a, 0x0a, 0x53, 0x4d, 0x53, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x07, 0x50, 0x75, 0x73, 0x68, 0x53, 0x4d, 0x53,
	0x12, 0x20, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53,
	0x4d, 0x53, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x12, 0x2b, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x4d, 0x53, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x53, 0x4d, 0x53, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xdb, 0x01, 0x0a, 0x0c, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x09, 0x50, 0x75, 0x73, 0x68, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x22, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x75, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x73, 0x12, 0x2d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2f,
	0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x44, 0x4c, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_open_platform_open_proto_rawDescOnce sync.Once
	file_proto_open_platform_open_proto_rawDescData = file_proto_open_platform_open_proto_rawDesc
)

func file_proto_open_platform_open_proto_rawDescGZIP() []byte {
	file_proto_open_platform_open_proto_rawDescOnce.Do(func() {
		file_proto_open_platform_open_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_open_platform_open_proto_rawDescData)
	})
	return file_proto_open_platform_open_proto_rawDescData
}

var file_proto_open_platform_open_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_open_platform_open_proto_goTypes = []interface{}{
	(*PushSMSRequest)(nil),               // 0: open_platform.v1.PushSMSRequest
	(*PushSMSResponse)(nil),              // 1: open_platform.v1.PushSMSResponse
	(*SMSTemplate)(nil),                  // 2: open_platform.v1.SMSTemplate
	(*GetAllSMSTemplatesRequest)(nil),    // 3: open_platform.v1.GetAllSMSTemplatesRequest
	(*GetAllSMSTemplatesResponse)(nil),   // 4: open_platform.v1.GetAllSMSTemplatesResponse
	(*PushEmailRequest)(nil),             // 5: open_platform.v1.PushEmailRequest
	(*PushEmailResponse)(nil),            // 6: open_platform.v1.PushEmailResponse
	(*EmailTemplate)(nil),                // 7: open_platform.v1.EmailTemplate
	(*GetAllEmailTemplatesRequest)(nil),  // 8: open_platform.v1.GetAllEmailTemplatesRequest
	(*GetAllEmailTemplatesResponse)(nil), // 9: open_platform.v1.GetAllEmailTemplatesResponse
}
var file_proto_open_platform_open_proto_depIdxs = []int32{
	2, // 0: open_platform.v1.GetAllSMSTemplatesResponse.templates:type_name -> open_platform.v1.SMSTemplate
	7, // 1: open_platform.v1.GetAllEmailTemplatesResponse.templates:type_name -> open_platform.v1.EmailTemplate
	0, // 2: open_platform.v1.SMSService.PushSMS:input_type -> open_platform.v1.PushSMSRequest
	3, // 3: open_platform.v1.SMSService.GetAllSMSTemplates:input_type -> open_platform.v1.GetAllSMSTemplatesRequest
	5, // 4: open_platform.v1.EmailService.PushEmail:input_type -> open_platform.v1.PushEmailRequest
	8, // 5: open_platform.v1.EmailService.GetAllEmailTemplates:input_type -> open_platform.v1.GetAllEmailTemplatesRequest
	1, // 6: open_platform.v1.SMSService.PushSMS:output_type -> open_platform.v1.PushSMSResponse
	4, // 7: open_platform.v1.SMSService.GetAllSMSTemplates:output_type -> open_platform.v1.GetAllSMSTemplatesResponse
	6, // 8: open_platform.v1.EmailService.PushEmail:output_type -> open_platform.v1.PushEmailResponse
	9, // 9: open_platform.v1.EmailService.GetAllEmailTemplates:output_type -> open_platform.v1.GetAllEmailTemplatesResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_open_platform_open_proto_init() }
func file_proto_open_platform_open_proto_init() {
	if File_proto_open_platform_open_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_open_platform_open_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushSMSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_open_platform_open_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushSMSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_open_platform_open_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMSTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_open_platform_open_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllSMSTemplatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_open_platform_open_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllSMSTemplatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_open_platform_open_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_open_platform_open_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_open_platform_open_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_open_platform_open_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllEmailTemplatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_open_platform_open_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllEmailTemplatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_open_platform_open_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_open_platform_open_proto_goTypes,
		DependencyIndexes: file_proto_open_platform_open_proto_depIdxs,
		MessageInfos:      file_proto_open_platform_open_proto_msgTypes,
	}.Build()
	File_proto_open_platform_open_proto = out.File
	file_proto_open_platform_open_proto_rawDesc = nil
	file_proto_open_platform_open_proto_goTypes = nil
	file_proto_open_platform_open_proto_depIdxs = nil
}
