/*
Code generated by config2go(https://github.com/xylonx/config2go)
DO NOT EDIT!
*/
package config

type Setting struct {
	Apm struct {
		Name          string `mapstructure:"name" json:"name" yaml:"name" `
		ReportBackend string `mapstructure:"report_backend" json:"report_backend" yaml:"report_backend" `
	} `mapstructure:"apm" json:"apm" yaml:"apm" `
	Application struct {
		GrpcHost           string   `mapstructure:"grpc_host" json:"grpc_host" yaml:"grpc_host" `
		GrpcPort           int64    `mapstructure:"grpc_port" json:"grpc_port" yaml:"grpc_port" `
		HttpAllowOrigin    []string `mapstructure:"http_allow_origin" json:"http_allow_origin" yaml:"http_allow_origin" `
		HttpHost           string   `mapstructure:"http_host" json:"http_host" yaml:"http_host" `
		HttpPort           int64    `mapstructure:"http_port" json:"http_port" yaml:"http_port" `
		HttpReadTimeout    int64    `mapstructure:"http_read_timeout" json:"http_read_timeout" yaml:"http_read_timeout" `
		HttpWriteTimeout   int64    `mapstructure:"http_write_timeout" json:"http_write_timeout" yaml:"http_write_timeout" `
		Mode               string   `mapstructure:"mode" json:"mode" yaml:"mode" `
		SessionDomain      string   `mapstructure:"session_domain" json:"session_domain" yaml:"session_domain" `
		SessionPath        string   `mapstructure:"session_path" json:"session_path" yaml:"session_path"`
		SessionSecret      string   `mapstructure:"session_secret" json:"session_secret" yaml:"session_secret" `
		TraefikRedirectUri string   `mapstructure:"traefik_redirect_uri" json:"traefik_redirect_uri" yaml:"traefik_redirect_uri" `
	} `mapstructure:"application" json:"application" yaml:"application" `
	Database struct {
		Postgres struct {
			Dsn            string `mapstructure:"dsn" json:"dsn" yaml:"dsn" `
			MaxIdleConn    int64  `mapstructure:"max_idle_conn" json:"max_idle_conn" yaml:"max_idle_conn" `
			MaxLifeSeconds int64  `mapstructure:"max_life_seconds" json:"max_life_seconds" yaml:"max_life_seconds" `
			MaxOpenConn    int64  `mapstructure:"max_open_conn" json:"max_open_conn" yaml:"max_open_conn" `
		} `mapstructure:"postgres" json:"postgres" yaml:"postgres" `
		Redis struct {
			Dsn string `mapstructure:"dsn" json:"dsn" yaml:"dsn" `
		} `mapstructure:"redis" json:"redis" yaml:"redis" `
	} `mapstructure:"database" json:"database" yaml:"database" `
	Lark struct {
		ClientId     string `mapstructure:"client_id" json:"client_id" yaml:"client_id" `
		ClientSecret string `mapstructure:"client_secret" json:"client_secret" yaml:"client_secret" `
		RedirectUri  string `mapstructure:"redirect_uri" json:"redirect_uri" yaml:"redirect_uri" `
	} `mapstructure:"lark" json:"lark" yaml:"lark" `
	OpenPlatform struct {
		Addr             string `mapstructure:"addr" json:"addr" yaml:"addr" `
		Token            string `mapstructure:"token" json:"token" yaml:"token"`
		VerificationCode struct {
			Email struct {
				TemplateId string `mapstructure:"template_id" json:"template_id" yaml:"template_id" `
			} `mapstructure:"email" json:"email" yaml:"email" `
			Sms struct {
				SignId     uint `mapstructure:"sign_id" json:"sign_id" yaml:"sign_id" `
				TemplateId uint `mapstructure:"template_id" json:"template_id" yaml:"template_id" `
			} `mapstructure:"sms" json:"sms" yaml:"sms" `
		} `mapstructure:"verification_code" json:"verification_code" yaml:"verification_code" `
	} `mapstructure:"open_platform" json:"open_platform" yaml:"open_platform" `
}
